service: scrpr-client

plugins:
  - serverless-stack-output

custom:
  output:
    file: ../cf-client.yml

provider:
  name: aws

resources:
  Resources:
    Bucket: ${file(resources/bucket.yml)}
    BucketPolicy: ${file(resources/bucket-policy.yml)}
    OriginAccessIdentity: ${file(resources/origin-access-identity.yml)}

  Outputs:
    OriginAccessIdentity:
      Value:
        Ref: OriginAccessIdentity
    BucketName:
      Value:
        Ref: Bucket