service: scrpr-batch

plugins:
  - serverless-stack-output

custom:
  output:
    file: cf-batch.yml

provider:
  name: aws

resources:
  Resources:
    BatchInstanceProfile: ${file(resources/batch-instance-profile.yml)}
    BatchInstanceRole: ${file(resources/batch-instance-role.yml)}
    BatchServiceRole: ${file(resources/batch-service-role.yml)}
    ComputeEnvironment: ${file(resources/compute-environment.yml)}
    ECRRepository: ${file(resources/ecr-repository.yml)}
    JobDefinition: ${file(resources/job-definition.yml)}
    JobQueue: ${file(resources/job-queue.yml)}

  Outputs:
    Region:
      Value:
        Ref: "AWS::Region"
    ECRURI:
      Value:
        Fn::Join: ["", [ { "Ref": "AWS::AccountId" }, '.dkr.ecr.', { Ref: "AWS::Region" }, ".amazonaws.com/", { Ref: ECRRepository } ]]