service: scrpr-batch

plugins:
  - serverless-stack-output

custom:
  output:
    file: cf-values.yml

provider:
  name: aws

resources:
  Resources:
    ECRRepository: ${file(resources/ecr-repository.yml)}

  Outputs:
    Region:
      Value:
        Ref: "AWS::Region"
    ECRURI:
      Value:
        Fn::Join: ["", [ { "Ref": "AWS::AccountId" }, '.dkr.ecr.', { Ref: "AWS::Region" }, ".amazonaws.com/", { Ref: ECRRepository } ]]