Type: AWS::Batch::ComputeEnvironment
Properties:
  ComputeEnvironmentName: scrpr-compute-environment
  Type: MANAGED
  ServiceRole:
    Ref: BatchServiceRole
  ComputeResources:
    Type: EC2
    DesiredvCpus: 1
    MaxvCpus: 1
    MinvCpus: 0
    Subnets:
      - ${file(../cf-domain.yml):SubnetPublicId}
    SecurityGroupIds:
      - ${file(../cf-domain.yml):SecurityGroupId}
    InstanceTypes:
      - m3.medium
    InstanceRole:
      Ref: BatchInstanceProfile