Type: AWS::Batch::ComputeEnvironment
Properties:
  ComputeEnvironmentName: scrpr-compute-environment
  Type: MANAGED
  ServiceRole:
    Ref: BatchServiceRole
  ComputeResources:
    Type: EC2
    DesiredvCpus: 1
    MaxvCpus: 10
    MinvCpus: 1
    Subnets:
      - ${file(../cf-hidden-values.yml):SubnetPublicId}
    SecurityGroupIds:
      - ${file(../cf-hidden-values.yml):SecurityGroupId}
    InstanceTypes:
      - m3.medium
    InstanceRole:
      Ref: BatchInstanceProfile