service: scrpr-service

plugins:
  - serverless-stack-output
  - serverless-webpack
  - serverless-offline

custom:
  output:
    file: cf-output.json
  serverless-offline:
    port: 5000
  webpack:
    packager: 'yarn'

provider:
  name: aws
  runtime: nodejs8.10
  apiName: scrpr-api
  versionFunctions: false
  endpointType: regional

functions:
  helloworld: ${file(functions/HelloWorld/function-hello-world.yml)}
  graphql: ${file(functions/GraphQL/function-graphql.yml)}

resources:
  Resources:
    CloudFrontDistribution: ${file(./resources/cloudfront.yml)}
    Authorizer: ${file(./resources/cognito-authorizer.yml)}
    UserPool: ${file(./resources/cognito-userpool.yml)}
    UserPoolClient: ${file(./resources/cognito-userpoolclient.yml)}

  Outputs:
    CloudFrontDomainName:
      Value:
        Fn::GetAtt: ['CloudFrontDistribution', 'DomainName']
    CloudFrontDistrubutionId:
      Value:
        Ref: CloudFrontDistribution
    UserPoolClient:
      Value:
        Ref: UserPoolClient
    UserPool:
      Value:
        Ref: UserPool
