service: scrpr-service

plugins:
  - serverless-stack-output
  - serverless-webpack
  - serverless-offline

custom:
  output:
    handler: scripts/output.handler
    file: ../cf-hidden-values.yml
  serverless-offline:
    port: 5000
  webpack:
    packager: 'yarn'
    includeModules:
      forceInclude:
        - knex # webpack fails to bundle knex
        - pg

provider:
  name: aws
  runtime: nodejs8.10
  apiName: scrpr-api
  versionFunctions: false
  endpointType: regional
  vpc: # Automatically adds AWSLambdaVPCAccessExecutionRole
    securityGroupIds:
      - Ref: SecurityGroup
    subnetIds:
      - Ref: SubnetA
      - Ref: SubnetB
  environment: ${file(resources/secrets.yml)}

functions:
  helloworld: ${file(functions/HelloWorld/function-hello-world.yml)}
  graphql: ${file(functions/GraphQL/function-graphql.yml)}

resources:
  Resources:
    VPC: ${file(resources/vpc.yml)}
    SecurityGroup: ${file(resources/security-group.yml)}
    SubnetA: ${file(resources/subnet-a.yml)}
    SubnetB: ${file(resources/subnet-b.yml)}
    DBSubnetGroup: ${file(resources/database-subnet-group.yml)}
    CloudFrontDistribution: ${file(resources/cloudfront.yml)}
    Authorizer: ${file(resources/cognito-authorizer.yml)}
    UserPool: ${file(resources/cognito-userpool.yml)}
    UserPoolClient: ${file(resources/cognito-userpoolclient.yml)}
    Database: ${file(resources/aurora-postgresqldatabase.yml)}

  Outputs:
    CloudFrontDomainName:
      Value:
        Fn::GetAtt: ['CloudFrontDistribution', 'DomainName']
    UserPoolClient:
      Value:
        Ref: UserPoolClient
    UserPool:
      Value:
        Ref: UserPool
    VPCId:
      Value:
        Ref: VPC
    SecurityGroupId:
      Value:
        Ref: SecurityGroup
    SubnetAId:
      Value:
        Ref: SubnetA
    SubnetBId:
      Value:
        Ref: SubnetB