service: scrpr-service

plugins:
  - serverless-stack-output
  - serverless-webpack
  - serverless-offline

custom:
  output:
    file: cf-api.json
  serverless-offline:
    port: 5000
  webpack:
    packager: 'yarn'
    includeModules:
      forceInclude:
        - knex # webpack fails to bundle knex
        - pg

provider:
  name: aws
  runtime: nodejs8.10
  apiName: scrpr-api
  versionFunctions: false
  endpointType: regional
  vpc: # Automatically adds AWSLambdaVPCAccessExecutionRole
    securityGroupIds:
      - ${file(../cf-domain.yml):SecurityGroupId}
    subnetIds:
      - ${file(../cf-domain.yml):SubnetAId}
      - ${file(../cf-domain.yml):SubnetBId}
      - ${file(../cf-domain.yml):SubnetPublicId}
  environment:
    DB_USER: ${file(../secrets.yml):DB_USER}
    DB_PASSWORD: ${file(../secrets.yml):DB_PASSWORD}
    DB_HOST: ${file(../cf-storage.yml):DatabaseHost}

functions:
  helloworld: ${file(functions/HelloWorld/function-hello-world.yml)}
  graphql: ${file(functions/GraphQL/function-graphql.yml)}

resources:
  Resources:
    CloudFrontDistribution: ${file(resources/cloudfront.yml)}
    Authorizer: ${file(resources/cognito-authorizer.yml)}
    UserPool: ${file(resources/cognito-userpool.yml)}
    UserPoolClient: ${file(resources/cognito-userpoolclient.yml)}

  Outputs:
    CloudFrontDomainName:
      Value:
        Fn::GetAtt: ['CloudFrontDistribution', 'DomainName']
    UserPoolClient:
      Value:
        Ref: UserPoolClient
    UserPool:
      Value:
        Ref: UserPool