service: scrpr-service

plugins:
  - serverless-stack-output
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  output:
    file: cf-output.json
  serverless-offline:
    port: 5000
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  apiName: scrpr-api
  versionFunctions: false
  endpointType: regional
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [ DynamoDbTable, Arn ]

functions:
  helloworld: ${file(./functions/HelloWorld/function-hello-world.yml)}

resources:
  Resources:
    CloudFrontDistribution: ${file(./resources/cloudfront.yml)}
    Authorizer: ${file(./resources/cognito-authorizer.yml)}
    UserPool: ${file(./resources/cognito-userpool.yml)}
    UserPoolClient: ${file(./resources/cognito-userpoolclient.yml)}
    DynamoDbTable: ${file(./resources/dynamodb-table.yml)}

  Outputs:
    CloudFrontDomainName:
      Value:
        Fn::GetAtt: ['CloudFrontDistribution', 'DomainName']
    CloudFrontDistrubutionId:
      Value:
        Ref: CloudFrontDistribution
    UserPoolClient:
      Value:
        Ref: UserPoolClient
    UserPool:
      Value:
        Ref: UserPool
    StacksRegion:
      Value:
        Ref: AWS::Region
    DbTableName:
      Value:
        Ref: DynamoDbTable