service: scrpr-domain

plugins:
  - serverless-stack-output

custom:
  output:
    file: ../cf-domain.yml

provider:
  name: aws

resources:
  Resources:
    InternetGateway: ${file(resources/internet-gateway.yml)}
    RoutePublic: ${file(resources/route-public.yml)}
    RouteTablePublic: ${file(resources/route-table-public.yml)}
    SecurityGroupDB: ${file(resources/security-group-db.yml)}
    SecurityGroupHTTP: ${file(resources/security-group-http.yml)}
    SubnetA: ${file(resources/subnet-a.yml)}
    SubnetB: ${file(resources/subnet-b.yml)}
    SubnetPublic: ${file(resources/subnet-public.yml)}
    SubnetRouteTableAssociationPublic: ${file(resources/subnet-route-table-association-public.yml)}
    VpcGatewayAttachment: ${file(resources/vpc-gateway-attachment.yml)}
    VPC: ${file(resources/vpc.yml)}

  Outputs:
    VPCId:
      Value:
        Ref: VPC
    SecurityGroupDBId:
      Value:
        Ref: SecurityGroupDB
    SecurityGroupHTTPId:
      Value:
        Ref: SecurityGroupHTTP
    SubnetAId:
      Value:
        Ref: SubnetA
    SubnetBId:
      Value:
        Ref: SubnetB
    SubnetPublicId:
      Value:
        Ref: SubnetPublic